version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "YourStrongPassword!"
    volumes:
      - mssql_data:/var/opt/mssql/data
      - ./initdb.sql:/initdb.sql
    networks:
      - backend-service-stm-network

  backend-service:
    container_name: backend-service-stm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-service-stm-network
    depends_on:
      - mssql

networks:
  backend-service-stm-network:
    name: backend-service-stm-network

volumes:
  mssql_data:


#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    cap_add:
#      - SYS_NICE
#    restart: always
#    environment:
#      - MYSQL_DATABASE=testdb
#      - MYSQL_ROOT_PASSWORD=password
#    ports:
#      - '3307:3307'
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
#    networks:
#      - default
#
#  backend-service:
#    container_name: backend-service-stm
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - default
#
#networks:
#  default:
#    name: backend-service-stm
#
#volumes:
#  mysql_data: